import { Contact } from './types';

export const MASTER_CONTACTS: Contact[] = [
  // --- LANDLORDS ---
  {
    id: 'contact-1',
    type: 'Landlord',
    name: 'Richard Thompson',
    email: 'r.thompson@example.com',
    phone: '+44 7700 900123',
    status: 'Active',
    createdDate: '2024-01-15',
    tags: ['Premium', 'Multi-Property'],
    address: '42 Knightsbridge',
    city: 'London',
    postcode: 'SW1X 7LY',
    portfolioValue: '£4.2M',
    propertyCount: 8,
    paymentMethod: 'Bank Transfer',
    linkedProperties: ['prop-1', 'prop-4'],
    assignedAgent: 'JD',
    lastContact: '2025-11-20',
    notes: 'Prefers email communication. Interested in expanding portfolio in Zone 1.'
  },
  {
    id: 'contact-2',
    type: 'Landlord',
    name: 'Sarah Mitchell',
    email: 'sarah.m@propertyinvest.co.uk',
    phone: '+44 7700 900234',
    status: 'Active',
    createdDate: '2023-08-22',
    tags: ['HMO Specialist'],
    address: '18 Richmond Road',
    city: 'London',
    postcode: 'TW9 2NA',
    portfolioValue: '£1.8M',
    propertyCount: 3,
    paymentMethod: 'Standing Order',
    linkedProperties: ['prop-3'],
    assignedAgent: 'SM',
    lastContact: '2025-11-18',
    notes: 'Specializes in HMOs. Looking for properties near universities.'
  },
  {
    id: 'contact-3',
    type: 'Landlord',
    name: 'David Chen',
    email: 'david.chen@gmail.com',
    phone: '+44 7700 900345',
    status: 'Active',
    createdDate: '2024-03-10',
    tags: ['First Time Landlord'],
    address: '5 Park Lane',
    city: 'London',
    postcode: 'W1K 1QA',
    portfolioValue: '£850K',
    propertyCount: 2,
    paymentMethod: 'Direct Debit',
    linkedProperties: ['prop-2'],
    assignedAgent: 'JD',
    lastContact: '2025-11-22',
    notes: 'New to property investment. Requires guidance on regulations.'
  },

  // --- TENANTS ---
  {
    id: 'contact-4',
    type: 'Tenant',
    name: 'Emma Wilson',
    email: 'emma.wilson@techcorp.com',
    phone: '+44 7700 900456',
    status: 'Active',
    createdDate: '2024-06-01',
    tags: ['Professional', 'Long-term'],
    address: 'The Shard, Apt 402',
    city: 'London',
    postcode: 'SE1 9SG',
    leaseStart: '2024-07-01',
    leaseEnd: '2025-07-01',
    rentAmount: '£3,500 pcm',
    depositPaid: '£4,038',
    linkedProperties: ['prop-1'],
    assignedAgent: 'JD',
    source: 'Rightmove',
    lastContact: '2025-11-15',
    notes: 'Works in finance. Excellent tenant, always pays on time.'
  },
  {
    id: 'contact-5',
    type: 'Tenant',
    name: 'James Porter',
    email: 'j.porter@studio.com',
    phone: '+44 7700 900567',
    status: 'Active',
    createdDate: '2024-09-15',
    tags: ['Creative', 'Pet Owner'],
    address: '14 High St',
    city: 'Camden',
    postcode: 'NW1 7JE',
    leaseStart: '2024-10-01',
    leaseEnd: '2025-10-01',
    rentAmount: '£1,900 pcm',
    depositPaid: '£2,192',
    linkedProperties: ['prop-2'],
    assignedAgent: 'JD',
    source: 'Zoopla',
    lastContact: '2025-11-10',
    notes: 'Graphic designer with small dog. Requested pet-friendly property.'
  },
  {
    id: 'contact-6',
    type: 'Tenant',
    name: 'Olivia Barnes',
    email: 'olivia.b@nhs.uk',
    phone: '+44 7700 900678',
    status: 'Active',
    createdDate: '2024-11-01',
    tags: ['NHS Staff'],
    address: '5 Garden Row',
    city: 'Brixton',
    postcode: 'SW9 8AB',
    leaseStart: '2024-11-15',
    leaseEnd: '2025-11-15',
    rentAmount: '£2,100 pcm',
    depositPaid: '£2,423',
    linkedProperties: ['prop-3'],
    assignedAgent: 'SM',
    source: 'Website',
    lastContact: '2025-11-12',
    notes: 'Works shifts at hospital. Needs quiet environment.'
  },

  // --- BUYERS ---
  {
    id: 'contact-7',
    type: 'Buyer',
    name: 'Michael Roberts',
    email: 'm.roberts@finance.com',
    phone: '+44 7700 900789',
    status: 'Active',
    createdDate: '2025-10-01',
    tags: ['First Time Buyer', 'Approved'],
    address: '22 Baker Street',
    city: 'London',
    postcode: 'NW1 6XE',
    budget: '£500K - £600K',
    preApproved: true,
    solicitor: 'Smithson & Partners LLP',
    linkedProperties: ['prop-5'],
    assignedAgent: 'JD',
    source: 'Rightmove',
    lastContact: '2025-11-21',
    notes: 'Looking for 2-bed in Zone 2. Mortgage approved by Nationwide.'
  },
  {
    id: 'contact-8',
    type: 'Buyer',
    name: 'Sophia Lee',
    email: 'sophia.lee@investment.co.uk',
    phone: '+44 7700 900890',
    status: 'Active',
    createdDate: '2025-09-15',
    tags: ['Investor', 'Cash Buyer'],
    address: '100 Canary Wharf',
    city: 'London',
    postcode: 'E14 5AB',
    budget: '£800K - £1.2M',
    preApproved: true,
    solicitor: 'Legal & General Solicitors',
    linkedProperties: ['prop-6', 'prop-7'],
    assignedAgent: 'SM',
    source: 'Website',
    lastContact: '2025-11-23',
    notes: 'Cash buyer looking for investment properties. No chain.'
  },

  // --- VENDORS ---
  {
    id: 'contact-9',
    type: 'Vendor',
    name: 'Robert Harrison',
    email: 'rob.harrison@gmail.com',
    phone: '+44 7700 900901',
    status: 'Active',
    createdDate: '2025-08-20',
    tags: ['Quick Sale', 'Downsizing'],
    address: '88 Hampstead Road',
    city: 'London',
    postcode: 'NW3 2PY',
    budget: '£750K',
    preApproved: false,
    solicitor: 'Barton & Co',
    linkedProperties: ['prop-8'],
    assignedAgent: 'JD',
    lastContact: '2025-11-19',
    notes: 'Downsizing to smaller property. Motivated seller.'
  },
  {
    id: 'contact-10',
    type: 'Vendor',
    name: 'Catherine Moore',
    email: 'c.moore@example.com',
    phone: '+44 7700 901012',
    status: 'Active',
    createdDate: '2025-07-10',
    tags: ['Relocation'],
    address: '12 Chelsea Harbour',
    city: 'London',
    postcode: 'SW10 0XA',
    budget: '£1.5M',
    preApproved: false,
    solicitor: 'Thompson Legal',
    linkedProperties: ['prop-9'],
    assignedAgent: 'SM',
    lastContact: '2025-11-17',
    notes: 'Relocating to Edinburgh for work. Needs to sell by March.'
  },

  // --- APPLICANTS ---
  {
    id: 'contact-11',
    type: 'Applicant',
    name: 'Alex Turner',
    email: 'alex.turner@startup.io',
    phone: '+44 7700 901123',
    status: 'Prospect',
    createdDate: '2025-11-20',
    tags: ['New Lead', 'Tech Professional'],
    city: 'London',
    budget: '£2,200 - £2,800 pcm',
    linkedProperties: ['prop-1', 'prop-2'],
    assignedAgent: 'JD',
    source: 'Zoopla',
    lastContact: '2025-11-22',
    notes: 'Just started new job in tech. Looking to move quickly.'
  },
  {
    id: 'contact-12',
    type: 'Applicant',
    name: 'Lucy Anderson',
    email: 'lucy.a@consulting.com',
    phone: '+44 7700 901234',
    status: 'Prospect',
    createdDate: '2025-11-18',
    tags: ['Graduate', 'Guarantor Available'],
    city: 'London',
    budget: '£1,500 - £1,900 pcm',
    linkedProperties: ['prop-2', 'prop-3'],
    assignedAgent: 'SM',
    source: 'Rightmove',
    lastContact: '2025-11-20',
    notes: 'Recent graduate with parental guarantor. Looking for Zone 2-3.'
  },

  // --- CONTRACTORS ---
  {
    id: 'contact-13',
    type: 'Contractor',
    name: 'Tom Jackson Plumbing',
    email: 'tom@jacksonplumbing.co.uk',
    phone: '+44 7700 901345',
    status: 'Active',
    createdDate: '2024-02-01',
    tags: ['Plumber', 'Emergency Call-Out'],
    address: '45 Tool Street',
    city: 'London',
    postcode: 'E1 6AN',
    trade: 'Plumbing',
    hourlyRate: '£65/hr',
    availability: 'Available',
    rating: 4.8,
    assignedAgent: 'JD',
    lastContact: '2025-11-21',
    notes: 'Gas Safe registered. 24/7 emergency service. Very reliable.'
  },
  {
    id: 'contact-14',
    type: 'Contractor',
    name: 'Elite Electrical Services',
    email: 'info@eliteelectrical.co.uk',
    phone: '+44 7700 901456',
    status: 'Active',
    createdDate: '2023-11-15',
    tags: ['Electrician', 'NICEIC Approved'],
    address: '22 Spark Lane',
    city: 'London',
    postcode: 'SW6 4TG',
    trade: 'Electrical',
    hourlyRate: '£70/hr',
    availability: 'Available',
    rating: 4.9,
    assignedAgent: 'SM',
    lastContact: '2025-11-19',
    notes: 'NICEIC approved. Handles all sizes of jobs. Fast response.'
  },
  {
    id: 'contact-15',
    type: 'Contractor',
    name: 'London Clean Pro',
    email: 'bookings@londoncleanpro.com',
    phone: '+44 7700 901567',
    status: 'Active',
    createdDate: '2024-05-20',
    tags: ['Cleaning', 'End of Tenancy'],
    address: '88 Tidy Road',
    city: 'London',
    postcode: 'N1 9QP',
    trade: 'Cleaning',
    hourlyRate: '£25/hr',
    availability: 'Available',
    rating: 4.7,
    assignedAgent: 'JD',
    lastContact: '2025-11-18',
    notes: 'Specialist in end-of-tenancy cleans. Eco-friendly products.'
  },
  {
    id: 'contact-16',
    type: 'Contractor',
    name: 'BuildRight Construction',
    email: 'contact@buildright.co.uk',
    phone: '+44 7700 901678',
    status: 'Active',
    createdDate: '2024-01-10',
    tags: ['Builder', 'Renovation Specialist'],
    address: '15 Builder Avenue',
    city: 'London',
    postcode: 'SE15 3HL',
    trade: 'General Building',
    hourlyRate: '£55/hr',
    availability: 'Busy',
    rating: 4.6,
    assignedAgent: 'SM',
    lastContact: '2025-11-16',
    notes: 'Great for renovations and extensions. Books up quickly.'
  },

  // --- SUPPLIERS ---
  {
    id: 'contact-17',
    type: 'Supplier',
    name: 'KeyMaster Locksmiths',
    email: 'info@keymasterlocks.com',
    phone: '+44 7700 901789',
    status: 'Active',
    createdDate: '2023-06-01',
    tags: ['Locksmith', 'Key Cutting'],
    address: '99 Lock Lane',
    city: 'London',
    postcode: 'W2 1HB',
    trade: 'Locksmith',
    hourlyRate: '£80/hr',
    availability: 'Available',
    rating: 4.9,
    assignedAgent: 'JD',
    lastContact: '2025-11-20',
    notes: 'Fast key cutting and lock changes. Master key systems available.'
  },
  {
    id: 'contact-18',
    type: 'Supplier',
    name: 'Property Signs Ltd',
    email: 'sales@propertysigns.co.uk',
    phone: '+44 7700 901890',
    status: 'Active',
    createdDate: '2024-04-12',
    tags: ['Signage', 'Branding'],
    address: '12 Sign Street',
    city: 'London',
    postcode: 'EC1V 2NX',
    trade: 'Signage',
    availability: 'Available',
    rating: 4.5,
    assignedAgent: 'SM',
    lastContact: '2025-11-14',
    notes: 'For sale/to let boards. Quick turnaround on custom signage.'
  },

  // --- LEADS ---
  {
    id: 'contact-19',
    type: 'Lead',
    name: 'Hannah Collins',
    email: 'hannah.c@email.com',
    phone: '+44 7700 901901',
    status: 'Prospect',
    createdDate: '2025-11-22',
    tags: ['New Lead', 'Unqualified'],
    budget: 'Not specified',
    assignedAgent: 'JD',
    source: 'Website',
    lastContact: '2025-11-22',
    notes: 'Enquired via website contact form. Needs follow-up.'
  },
  {
    id: 'contact-20',
    type: 'Lead',
    name: 'Daniel Wright',
    email: 'd.wright@example.com',
    phone: '+44 7700 902012',
    status: 'Prospect',
    createdDate: '2025-11-21',
    tags: ['New Lead', 'Phone Enquiry'],
    budget: '£1,800 - £2,200 pcm',
    assignedAgent: 'SM',
    source: 'Phone',
    lastContact: '2025-11-21',
    notes: 'Called asking about rental properties in South London.'
  }
];
