import { Property } from './types';

export const MASTER_PROPERTIES: Property[] = [
    // --- LETTINGS ---
    {
        id: 'prop-1',
        address: 'The Shard, Apt 402, London Bridge St',
        postcode: 'SE1 9SG',
        price: '£3,500 pcm',
        type: 'Lettings',
        status: 'Available',
        bedrooms: 2,
        bathrooms: 2,
        sqft: 1200,
        image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
        agent: 'JD',
        portalStatus: { rightmove: true, zoopla: true, website: true },
        stats: { views: 1240, enquiries: 45 },
        description: "A magnificent two bedroom apartment located within the iconic Shard. Floor-to-ceiling windows offer breathtaking views of the London skyline.",
        features: ["Concierge", "Gym", "Panoramic Views", "Luxury Fittings"],
        additionalDetails: { councilTax: 'H', deposit: '£4038', tenure: 'Long Let', availability: 'Now' },
        epcRating: 'B',
        media: { floorPlanUrl: 'yes' },
        location: { lat: 51.5045, lng: -0.0865 }
    },
    {
        id: 'prop-2',
        address: '14 High St, Camden',
        postcode: 'NW1 7JE',
        price: '£1,900 pcm',
        type: 'Lettings',
        status: 'Under Offer',
        bedrooms: 1,
        bathrooms: 1,
        sqft: 650,
        image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
        agent: 'JD',
        portalStatus: { rightmove: true, zoopla: false, website: true },
        stats: { views: 850, enquiries: 32 },
        description: "Charming one bed in the heart of Camden. Moments from the market and lock, this flat features exposed brickwork and high ceilings.",
        features: ["Close to Tube", "Newly Renovated", "Exposed Brick"],
        additionalDetails: { councilTax: 'D', deposit: '£2192', tenure: 'Long Let', availability: 'Oct 1st' },
        epcRating: 'C',
        media: {},
        location: { lat: 51.5390, lng: -0.1426 }
    },
    {
        id: 'prop-3',
        address: '5 Garden Row, Brixton',
        postcode: 'SW9 8AB',
        price: '£2,100 pcm',
        type: 'Lettings',
        status: 'Let Agreed',
        bedrooms: 2,
        bathrooms: 1,
        sqft: 750,
        image: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80',
        agent: 'SM',
        portalStatus: { rightmove: true, zoopla: true, website: false },
        stats: { views: 2200, enquiries: 12 },
        description: "Victorian conversion with private garden. Perfect for professionals sharing.",
        features: ["Private Garden", "Period Features", "Pet Friendly"],
        additionalDetails: { councilTax: 'C', deposit: '£2423', tenure: 'Long Let', availability: 'Nov 15th' },
        epcRating: 'D',
        media: {},
        location: { lat: 51.4613, lng: -0.1156 }
    },
    {
        id: 'prop-4',
        address: 'Penthouse A, Soho',
        postcode: 'W1D 3QE',
        price: '£5,000 pcm',
        type: 'Lettings',
        status: 'Let Agreed',
        bedrooms: 3,
        bathrooms: 3,
        sqft: 1800,
        image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
        agent: 'BM',
        portalStatus: { rightmove: true, zoopla: true, website: true },
        stats: { views: 3400, enquiries: 8 },
        description: "Luxury living in the heart of Soho. Direct lift access and expansive roof terrace.",
        features: ["Roof Terrace", "Smart Home", "Private Lift", "Air Conditioning"],
        additionalDetails: { councilTax: 'H', deposit: '£5769', tenure: 'Long Let', availability: 'Taken' },
        epcRating: 'B',
        media: {},
        location: { lat: 51.5136, lng: -0.1365 }
    },
    {
        id: 'prop-8',
        address: '12B High Street, Clapham',
        postcode: 'SW4 7AA',
        price: '£1,800 pcm',
        type: 'Lettings',
        status: 'Under Offer',
        bedrooms: 1,
        bathrooms: 1,
        sqft: 550,
        image: 'https://images.unsplash.com/photo-1505691723518-36a5ac3be353?auto=format&fit=crop&w=800&q=80',
        agent: 'JD',
        portalStatus: { rightmove: true, zoopla: false, website: true },
        stats: { views: 600, enquiries: 18 },
        description: "Top floor flat moments from the common. Bright and airy with modern kitchen.",
        features: ["Furnished", "Open Plan", "Bright"],
        additionalDetails: { councilTax: 'C', deposit: '£2076', tenure: 'Long Let', availability: 'Oct 10th' },
        epcRating: 'C',
        media: {},
        location: { lat: 51.4620, lng: -0.1380 }
    },
    {
        id: 'prop-9',
        address: '22 Marina Way, Canary Wharf',
        postcode: 'E14 5GL',
        price: '£2,800 pcm',
        type: 'Lettings',
        status: 'Available',
        bedrooms: 2,
        bathrooms: 2,
        sqft: 950,
        image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
        agent: 'SM',
        portalStatus: { rightmove: true, zoopla: true, website: true },
        stats: { views: 500, enquiries: 15 },
        description: "Modern apartment with balcony overlooking the dock.",
        features: ["Balcony", "Water Views", "24h Porter"],
        additionalDetails: { councilTax: 'F', deposit: '£3230', tenure: 'Long Let', availability: 'Now' },
        epcRating: 'B',
        media: {},
        location: { lat: 51.5033, lng: -0.0270 }
    },
    {
        id: 'prop-10',
        address: '7 Elm Street, Shoreditch',
        postcode: 'E1 6AW',
        price: '£2,400 pcm',
        type: 'Lettings',
        status: 'Available',
        bedrooms: 1,
        bathrooms: 1,
        sqft: 800,
        image: 'https://images.unsplash.com/photo-1501183638710-841dd1904471?auto=format&fit=crop&w=800&q=80',
        agent: 'JD',
        portalStatus: { rightmove: true, zoopla: true, website: true },
        stats: { views: 920, enquiries: 28 },
        description: "Industrial style loft in converted warehouse.",
        features: ["Loft Style", "High Ceilings", "Wood Floors"],
        additionalDetails: { councilTax: 'E', deposit: '£2769', tenure: 'Long Let', availability: 'Nov 1st' },
        epcRating: 'D',
        media: {},
        location: { lat: 51.5229, lng: -0.0777 }
    },

    // --- SALES ---
    {
        id: 'prop-5',
        address: '88 The Avenue, Balham',
        postcode: 'SW12 9AW',
        price: '£750,000',
        type: 'Sales',
        status: 'Under Offer',
        bedrooms: 3,
        bathrooms: 1,
        sqft: 1100,
        image: 'https://images.unsplash.com/photo-1600596542815-27bfef980dc8?auto=format&fit=crop&w=800&q=80',
        agent: 'TS',
        portalStatus: { rightmove: true, zoopla: true, website: true },
        stats: { views: 1500, enquiries: 15 },
        description: "Spacious family home with potential to extend (STPP). Large rear garden.",
        features: ["Freehold", "Chain Free", "Near Schools"],
        additionalDetails: { councilTax: 'E', deposit: 'N/A', tenure: 'Freehold', availability: 'On Completion' },
        epcRating: 'D',
        media: {},
        location: { lat: 51.4428, lng: -0.1525 }
    },
    {
        id: 'prop-6',
        address: '15 Sandybrook Close, Romiley',
        postcode: 'SK6 3JB',
        price: '£575,000',
        type: 'Sales',
        status: 'Available',
        bedrooms: 4,
        bathrooms: 3,
        sqft: 1650,
        image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
        agent: 'DR',
        portalStatus: { rightmove: true, zoopla: true, website: true },
        stats: { views: 450, enquiries: 12 },
        description: "Modern detached house in a quiet cul-de-sac. Double garage and landscaped gardens.",
        features: ["Double Garage", "En-suite", "Large Garden"],
        additionalDetails: { councilTax: 'F', deposit: 'N/A', tenure: 'Freehold', availability: 'Immediate' },
        epcRating: 'B',
        media: { virtualTourUrl: 'yes', videoUrl: 'yes' },
        location: { lat: 53.4123, lng: -2.1045 }
    },
    {
        id: 'prop-7',
        address: '39 Church Lane, Marple',
        postcode: 'SK6 6AA',
        price: '£350,000',
        type: 'Sales',
        status: 'Sold',
        bedrooms: 2,
        bathrooms: 1,
        sqft: 900,
        image: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b91d?auto=format&fit=crop&w=800&q=80',
        agent: 'DR',
        portalStatus: { rightmove: false, zoopla: false, website: true },
        stats: { views: 2100, enquiries: 25 },
        description: "Character cottage close to village amenities. Original stone features.",
        features: ["Stone Built", "Log Burner", "Cottage Garden"],
        additionalDetails: { councilTax: 'C', deposit: 'N/A', tenure: 'Freehold', availability: 'Sold' },
        epcRating: 'E',
        media: {},
        location: { lat: 53.3982, lng: -2.0621 }
    },
    {
        id: 'prop-11',
        address: '20 Ingram St, Queens',
        postcode: 'NY 11375',
        price: '£850,000',
        type: 'Sales',
        status: 'Available',
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1400,
        image: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80',
        agent: 'PP',
        portalStatus: { rightmove: true, zoopla: false, website: true },
        stats: { views: 1100, enquiries: 40 },
        description: "Classic detached home with modern upgrades.",
        features: ["Driveway", "Newly Fitted Kitchen", "Quiet Street"],
        additionalDetails: { councilTax: 'F', deposit: 'N/A', tenure: 'Freehold', availability: 'Chain Free' },
        epcRating: 'C',
        media: {},
        location: { lat: 40.7282, lng: -73.7949 }
    },
    {
        id: 'prop-12',
        address: 'Oscorp Manor, Westchester',
        postcode: 'NY 10504',
        price: '£2,500,000',
        type: 'Sales',
        status: 'Available',
        bedrooms: 8,
        bathrooms: 6,
        sqft: 8500,
        image: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80',
        agent: 'NO',
        portalStatus: { rightmove: true, zoopla: true, website: true },
        stats: { views: 5000, enquiries: 5 },
        description: "Grand estate with sprawling grounds.",
        features: ["Gated Entry", "Pool", "Tennis Court", "Guest House"],
        additionalDetails: { councilTax: 'H', deposit: 'N/A', tenure: 'Freehold', availability: 'Immediate' },
        epcRating: 'D',
        media: {},
        location: { lat: 41.1220, lng: -73.7949 }
    }
];